### ISSUE TITLE
logo.png isn't precompiled

### ISSUE THREAD

**Issue by rchekaluk** [opengovernment/askthem-legacy#101]
oglocal is down, david indicated this was correlated with one of his recent commits, though I cannot find anything in those that seems to be correlated.

The Heroku log is throwing exceptions like the below. Is there a deployment step missing? If so is it possible to add it to [OpenGovernment dev notes 7-2-13](https://docs.google.com/a/opencongress.org/document/d/18d3qi2e7neXMUisW4JSEAAz-1n2P-SXXu_6bqoAkx4k/edit#heading=h.5dq4s0iq5yyk)?:

```
2013-09-09T18:40:23.414910+00:00 app[web.1]: Started GET "/ny/questions" for 64.72.75.194 at 2013-09-09 18:40:23 +0000
2013-09-09T18:40:24.196402+00:00 app[web.1]: ** [Airbrake] Success: Net::HTTPOK
2013-09-09T18:40:24.199427+00:00 app[web.1]: 
2013-09-09T18:40:24.199427+00:00 app[web.1]: ActionView::Template::Error (logo.png isn't precompiled):
2013-09-09T18:40:24.199427+00:00 app[web.1]:     17:   <meta property="og:site_name" content="OpenGovernment">
2013-09-09T18:40:24.199427+00:00 app[web.1]:     18:   <meta property="og:type" content="website">
2013-09-09T18:40:24.199427+00:00 app[web.1]:     19:   <meta property="og:url" content="<%= current_url %>">
2013-09-09T18:40:24.199427+00:00 app[web.1]:     20:   <meta property="og:image" content="<%= og_image %>">
2013-09-09T18:40:24.199427+00:00 app[web.1]:     21:   <meta property="og:locale" content="en_US">
2013-09-09T18:40:24.199427+00:00 app[web.1]:     22:   <meta property="fb:admins" content="100002666906486">
2013-09-09T18:40:24.199427+00:00 app[web.1]:     23:   <meta property="fb:app_id" content="124751554385930">
2013-09-09T18:40:24.199427+00:00 app[web.1]:   app/helpers/application_helper.rb:94:in `og_image'
2013-09-09T18:40:24.199676+00:00 app[web.1]:   app/views/layouts/application.html.erb:20:in `_app_views_layouts_application_html_erb___3104824133953986500_63382800'
2013-09-09T18:40:24.199676+00:00 app[web.1]:   app/controllers/questions_controller.rb:11:in `index'
2013-09-09T18:40:24.199676+00:00 app[web.1]: 
2013-09-09T18:40:24.199676+00:00 app[web.1]: 
```

**Comment by walter** [comment]
The rake asset:pipeline task was failing to run because of a dependency I had added to the Rakefile.

The dependency is mainly for tests which is why I hadn't added it to the Gemfile under the production group. However it is required in the Rakefile and so needs to be added for all groups.

Added to Gemfile for production and fixed issue.
